### ISSUE TITLE
Fehler 1785 bei Constraints

### ISSUE THREAD

**Issue by micgro42** [fa35/Library150329#1]
In dem create_tables_of_library.sql sind bereits foreign-keys enthalten. Die doppeln sich dann mit denen aus  own_constraints.sql

**Comment by ghost** [comment]
wie habe ich die dann anlegen könne?

**Comment by ghost** [comment]
Sieh dir mal das an, das ist auch interessant:

USE [Bibliothek]
GO
SELECT name, create_date
FROM sys.objects
WHERE type_desc Like '%CONSTRAINT'
ORDER BY create_date DESC;
GO

**Comment by ghost** [comment]
Schon vorhandene Constraints übersehen
